name:                RunRunCompiler
version:             0.1.0.0
github:              "kengohirata/RunRunCompiler"
license:             BSD3
author:              "KengoHirata"
maintainer:          "s3beeeekbbn.t@gmail.com"
copyright:           "2020 KengoHirata"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kengohirata/RunRunCompiler#readme>

dependencies:
- base >= 4.7 && < 5
- array
- mtl
- containers
- algebraic-graphs

library:
  source-dirs: src
  c-sources: src/Back/float.c

executables:
  min-caml:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - RunRunCompiler

tests:
  RunRunCompiler-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - RunRunCompiler
